rsync -a --delete  --exclude-from=/home/lewis/projects/lwood-solutions/exclude_folders -i /home/lewis/projects/lwood-solutions/. km:sites/lwood-solutions/.



     --ignore-missing-args   ignore missing source args without error                                                                                                                                                                                                         
--delete-missing-args   delete missing source args from destination                                                                                                                                                                                                      
--ignore-errors         delete even if there are I/O errors                                                                                                                                                                                                              
--force                 force deletion of directories even if not empty                                                                                                                                                                                                  
--max-delete=NUM        don't delete more than NUM files                                                                                                                                                                                                                 
--max-size=SIZE         don't transfer any file larger than SIZE                                                                                                                                                                                                         
--min-size=SIZE         don't transfer any file smaller than SIZE                                                                                                                                                                                                        
--partial               keep partially transferred files                                                                                                                                                                                                                 
--partial-dir=DIR       put a partially transferred file into DIR                                                                                                                                                                                                        
--delay-updates         put all updated files into place at transfer's end                                                                                                                                                                                               
-m, --prune-empty-dirs      prune empty directory chains from the file-list                                                                                                                                                                                                  
--numeric-ids           don't map uid/gid values by user/group name                                                                                                                                                                                                      
--usermap=STRING        custom username mapping                                                                                                                                                                                                                          
--groupmap=STRING       custom groupname mapping                                                                                                                                                                                                                         
--chown=USER:GROUP      simple username/groupname mapping                                                                                                                                                                                                                
--timeout=SECONDS       set I/O timeout in seconds                                                                                                                                                                                                                       
--contimeout=SECONDS    set daemon connection timeout in seconds                                                                                                                                                                                                         
-I, --ignore-times          don't skip files that match in size and mod-time                                                                                                                                                                                                 
-M, --remote-option=OPTION  send OPTION to the remote side only                                                                                                                                                                                                              
--size-only             skip files that match in size                                                                                                                                                                                                                    
-@, --modify-window=NUM     set the accuracy for mod-time comparisons                                                                                                                                                                                                        
-T, --temp-dir=DIR          create temporary files in directory DIR                                                                                                                                                                                                          
-y, --fuzzy                 find similar file for basis if no dest file                                                                                                                                                                                                      
--compare-dest=DIR      also compare destination files relative to DIR                                                                                                                                                                                                   
--copy-dest=DIR         ... and include copies of unchanged files                                                                                                                                                                                                        
--link-dest=DIR         hardlink to files in DIR when unchanged                                                                                                                                                                                                          
-z, --compress              compress file data during the transfer                                                                                                                                                                                                           
--compress-level=NUM    explicitly set compression level                                                                                                                                                                                                                 
--skip-compress=LIST    skip compressing files with a suffix in LIST                                                                                                                                                                                                     
-C, --cvs-exclude           auto-ignore files the same way CVS does                                                                                                                                                                                                          
-f, --filter=RULE           add a file-filtering RULE                                                                                                                                                                                                                        
-F                          same as --filter='dir-merge /.rsync-filter'                                                                                                                                                                                                      
repeated: --filter='- .rsync-filter'                                                                                                                                                                                                             
--exclude=PATTERN       exclude files matching PATTERN                                                                                                                                                                                                                   
--exclude-from=FILE     read exclude patterns from FILE                                                                                                                                                                                                                  
--include=PATTERN       don't exclude files matching PATTERN                                                                                                                                                                                                             
--include-from=FILE     read include patterns from FILE                                                                                                                                                                                                                  
--files-from=FILE       read list of source-file names from FILE                                                                                                                                                                                                         
-0, --from0                 all *-from/filter files are delimited by 0s                                                                                                                                                                                                      
-s, --protect-args          no space-splitting; only wildcard special-chars                                                                                                                                                                                                  
--trust-sender          trust the remote sender's file list                                                                                                                                                                                                              
--address=ADDRESS       bind address for outgoing socket to daemon                                                                                                                                                                                                       
--port=PORT             specify double-colon alternate port number                                                                                                                                                                                                       
--sockopts=OPTIONS      specify custom TCP options                                                                                                                                                                                                                       
--blocking-io           use blocking I/O for the remote shell                                                                                                                                                                                                            
--stats                 give some file-transfer stats                                                                                                                                                                                                                    
-8, --8-bit-output          leave high-bit chars unescaped in output                                                                                                                                                                                                         
-h, --human-readable        output numbers in a human-readable format                                                                                                                                                                                                        
--progress              show progress during transfer                                                                                                                                                                                                                    
-P                          same as --partial --progress                                                                                                                                                                                                                     
-i, --itemize-changes       output a change-summary for all updates                                                                                                                                                                                                          
--out-format=FORMAT     output updates using the specified FORMAT                                                                                                                                                                                                        
--log-file=FILE         log what we're doing to the specified FILE                                                                                                                                                                                                       
--log-file-format=FMT   log updates using the specified FMT                                                                                                                                                                                                              
--password-file=FILE    read daemon-access password from FILE                                                                                                                                                                                                            
--list-only             list the files instead of copying them                                                                                                                                                                                                           
--bwlimit=RATE          limit socket I/O bandwidth                                                                                                                                                                                                                       
--stop-at=y-m-dTh:m     Stop rsync at year-month-dayThour:minute                                                                                                                                                                                                         
--time-limit=MINS       Stop rsync after MINS minutes have elapsed                                                                                                                                                                                                       
--outbuf=N|L|B          set output buffering to None, Line, or Block                                                                                                                                                                                                     
--write-batch=FILE      write a batched update to FILE                                                                                                                                                                                                                   
--only-write-batch=FILE like --write-batch but w/o updating destination                                                                                                                                                                                                  
--read-batch=FILE       read a batched update from FILE                                                                                                                                                                                                                  
--protocol=NUM          force an older protocol version to be used                                                                                                                                                                                                       
--iconv=CONVERT_SPEC    request charset conversion of filenames                                                                                                                                                                                                          
--checksum-seed=NUM     set block/file checksum seed (advanced)                                                                                                                                                                                                          
--noatime               do not alter atime when opening source files                                                                                                                                                                                                     
-4, --ipv4                  prefer IPv4                                                                                                                                                                                                                                      
-6, --ipv6                  prefer IPv6                                                                                                                                                                                                                                      
--version               print version number                                                                                                                                                                                                                             
(-h) --help                  show this help (-h is --help only if used alone)                                                                                                                                                                                                 
Use "rsync --daemon --help" to see the daemon-mode command-line options.                                                                                                                                                                                                      
Please see the rsync(1) and rsyncd.conf(5) man pages for full documentation.                                                                                                                                                                                                  
See http://rsync.samba.org/ for updates, bug reports, and answers                                                                                                                                                                                                             
lewis-i9$


***
