apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
     app: home-react-app
  template:
    metadata:
      labels:
        app: home-react-app
    spec:
      containers:
      - name: home-react-app
        image: lewislwood/home-react-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
 name: home-react-app
spec:
  type: NodePort
  selector:
    app: home-react-app
  ports:
    - port: 3000
      protocol: TCP

      targetPort: 3000
      nodePort: 31000
      